apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth #how to find all the pods that is going to create
  template: #how to create each pod that is the deployment is going to create
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: goktayincekara/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1 #default type of the service is the cluster IP service. Thats why we are not providing any type
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth #We want to find all the pods with the name of app: auth (in metadata -> labels)
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000 #Bcs we are listening 3000 in the auth implementation
#With auth-srv name, any other pod or anything else inside of our cluster can access this service and therefore the pod that it governs
#access to by trying to go to http://auth-srv  (http://auth-srv/api/users/currentuser)
